### ISSUE TITLE
Expand Documentation

### ISSUE THREAD

**Issue by hephaestoskin** [himurovich/MODX-mChimpX#10]
Any way the documentation could be expanded with a couple of examples? Took me a while to grasp everything (without glitches) and it could be really helpful to people, especially newbies at modx.

**Comment by himurovich** [comment]
Hello @hephaestoskin, documentation is in progress and will be updated soon (well, if this is still actual for you :) )

**Comment by himurovich** [comment]
I've updated readme file, hope this example will help more. Please let me know any questions.
https://github.com/himurovich/MODX-mChimpX/blob/master/README.md
