### ISSUE TITLE
Mailchimp API v3

### ISSUE THREAD

**Issue by Jorgenh** [himurovich/MODX-mChimpX#13]
It seems like this Xtra is not compatibel with API v3? http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/

Will this be added?

**Comment by lkfranklin** [comment]
Having the same issue - but this extra hasn't been updated for years so I'm guessing there's not much hope.

**Comment by MedusaDelft** [comment]
MailChimp says the older api-versions can not be used after 2016.  So...   I have a new installation to do (first one), but all available modx-packages are not maintained. Any suggestions?

**Comment by Jorgenh** [comment]
@MedusaDelft I used https://github.com/drewm/mailchimp-api recently. It's just a wrapper but with some tweaking you can probably make it fit your needs.

**Comment by sonicpunk** [comment]
Is this true?  I just implemented this extra and it is working.

**Comment by joyceDesignbase** [comment]
I just installed this and it works! (revo 2.4.0)

**Comment by himurovich** [comment]
> 
> 
> It seems like this Xtra is not compatibel with API v3? http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/
> 
> Will this be added?

Hello @Jorgenh, 
sorry a bit late but work has been started, hope soon let you know about new API support

**Comment by Jorgenh** [comment]
Thanks @himurovich!
I already wrote a snippet of my own to deal with API v3 but i guess others using this extra will be grateful if you add support soon. v1 has already shutdown.

**Comment by himurovich** [comment]
@Jorgenh it was easier and faster to implement API 2.0 support firstly (Maichimp recommends 3.0 usage, anyway there are no expiry dates for 2.0 now). So 3.0 will be implemented asap, but now anyone can use actual 2.0 support. Github code is up to date while waiting for Extra update with transport package.
